//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments_Tests
    {
        public int ID { get; set; }
        public Nullable<long> Appointment_ID { get; set; }
        public Nullable<int> Test_ID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Test Test { get; set; }
    }
}
