//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Appointments_Tests = new HashSet<Appointments_Tests>();
        }
    
        public long ID { get; set; }
        public string Full_Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Email_Address { get; set; }
        public string Phone_Number { get; set; }
        public string Home_Address { get; set; }
        public Nullable<System.DateTime> Date_Of_Appo { get; set; }
        public Nullable<decimal> Total_price { get; set; }
        public Nullable<decimal> Amount_paid { get; set; }
        public Nullable<int> Billing_ID { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments_Tests> Appointments_Tests { get; set; }
    }
}
