//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int ChatMessage_ID { get; set; }
        public Nullable<int> ChatRoom_ID { get; set; }
        public Nullable<int> SenderId { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
        public string SenderType { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
    }
}
