//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contact_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string sub { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
        public string admin_response { get; set; }
        public Nullable<System.DateTime> response_date { get; set; }
        public Nullable<int> status { get; set; }
    }
}
