//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterPieceEntities : DbContext
    {
        public MasterPieceEntities()
            : base("name=MasterPieceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Appointments_Tests> Appointments_Tests { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<ChatRoom> ChatRooms { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Lab_Tech> Lab_Tech { get; set; }
        public virtual DbSet<Package_Tests> Package_Tests { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Test_Order> Test_Order { get; set; }
        public virtual DbSet<Test_Order_Tests> Test_Order_Tests { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
    }
}
