//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Notification_ID { get; set; }
        public Nullable<int> Doctor_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<System.DateTime> Notification_Date { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Lab_Tech Lab_Tech { get; set; }
        public virtual Test_Order Test_Order { get; set; }
    }
}
