//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test_Order()
        {
            this.Test_Order_Tests = new HashSet<Test_Order_Tests>();
        }
    
        public int Order_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Tech_ID { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<int> Discount_Persent { get; set; }
        public Nullable<decimal> Amount_Paid { get; set; }
        public string Status { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Order_Tests> Test_Order_Tests { get; set; }
    }
}
