//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.Appointments_Tests = new HashSet<Appointments_Tests>();
            this.Package_Tests = new HashSet<Package_Tests>();
            this.Test_Order_Tests = new HashSet<Test_Order_Tests>();
        }
    
        public int Test_ID { get; set; }
        public string Test_Name { get; set; }
        public string Alternative_Name { get; set; }
        public string Components { get; set; }
        public string Normal_Range { get; set; }
        public string Unit { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Inventory { get; set; }
        public string Sample_Type { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments_Tests> Appointments_Tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Tests> Package_Tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Order_Tests> Test_Order_Tests { get; set; }
    }
}
