//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Order_Tests
    {
        public int ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Test_ID { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> Date_Of_Result { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
    
        public virtual Test_Order Test_Order { get; set; }
        public virtual Test Test { get; set; }
    }
}
